version: "3.9"
services:
  emotebot:
    image: vendicated/emote-bot
    build: .
    restart: always
    env_file:
      - bot.env
      - pg.env
    links:
      - postgres

  postgres:
    image: postgres
    restart: always
    env_file: pg.env
    volumes:
      - emotebot-db:/var/lib/postgresql/data

volumes:
  emotebot-db:
